name: CD

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master # Push events on master + devel branch
      - devel
      - firstcommit

    tags:
      - "*" # Test all pushed tags

  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked

  pull_request_review:
    types:
      - submitted

  status: {}
env:
  RELEASE: release

jobs:
  build:
    runs-on: [ubuntu-latest]
    name: Build and run unit tests.
    steps:
      - uses: actions/checkout@v2

      - name: Install Gradle Wrapper (this step should not be needed)
        run: |
          pushd uamp
          gradle wrapper
          popd

      - name: Build for android
        run: |
          pushd uamp
          ./gradlew build
          popd
