name: CD
on:
  push:
    branches:
      - master
      - main
      - devel
      - develop
    tags:
      - "*"
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}
env:
  RELEASE: release
jobs:
  build:
    runs-on:
      - ubuntu-latest
    name: Build, and run unit tests.
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build for Android Automotive
        uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: uamp
          arguments: assemble
      - name: Unit tests (debug)
        if: (github.ref == 'refs/heads/master') || (github.ref == 'refs/heads/devel')
        run: |
          pushd uamp
          ./gradlew testDebugUnitTest
          popd
      - name: Unit tests (release)
        if: (github.ref == 'refs/heads/master') || (github.ref == 'refs/heads/devel')
        run: |
          pushd uamp
          ./gradlew testReleaseUnitTest
          popd
