name: CD

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master # Push events on master + devel branch
      - devel

    tags:
      - '*' # Test all pushed tags

  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked

  pull_request_review:
    types:
      - submitted

  status: {}
env:
  RELEASE: release

jobs:
  build:
    runs-on: self-hosted
    name: Build and run unit tests.
    steps:

    - uses: actions/checkout@v1
    
    - name: yarn install
      run: |
        pushd mobile_apps
        yarn install
        popd

    - name: Run javascript unit tests.
      run: |
        pushd mobile_apps
        yarn run test
        popd

    - name: Build for android
      run: |
        pushd mobile_apps
        yarn run android:buildDebug
        popd

    - name: Build for iOS
      run: |
        pushd mobile_apps/ios
        pod install
        xcodebuild -workspace TripLog.xcworkspace -scheme TripLog -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED="NO" CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO" | xcpretty
        popd
